// apps/frontend/src/ui/Badge.svelte
<script lang="ts">
  type BadgeType = "success" | "warning" | "danger";
  export let type: BadgeType;

  let badgeClass = "";

  $: {
    if (type === "success") {
      badgeClass = "badge__success";
    } else if (type === "warning") {
      badgeClass = "badge__warning";
    } else if (type === "danger") {
      badgeClass = "badge__danger";
    }
  }
</script>

<span class={`badge ${badgeClass}`}><slot /></span>

<style lang="postcss">
  .badge {
    @apply text-xs font-semibold mr-2 px-2.5 py-0.5 rounded;
  }

  .badge__success {
    @apply bg-green-100 text-green-800 dark:bg-green-200 dark:text-green-900;
  }

  .badge__warning {
    @apply bg-yellow-100 text-yellow-800 dark:bg-yellow-200 dark:text-yellow-900;
  }

  .badge__danger {
    @apply bg-red-100 text-red-800 dark:bg-red-200 dark:text-red-900;
  }
</style>

// apps/next13/components/Badge/Badge.tsx
import React from "react";
import clsx from "clsx";

interface BadgeProps {
  type: "success" | "warning";
  children: React.ReactNode;
}

const badgeStyles = {
  badge: "text-xs font-semibold mr-2 px-2.5 py-0.5 rounded",
  success: "bg-green-800 text-green-200 dark:bg-green-200 dark:text-green-800",
  warning:
    "bg-yellow-800 text-yellow-200 dark:bg-yellow-200 dark:text-yellow-800",
  danger: "bg-red-800 text-red-200 dark:bg-red-200 dark:text-red-800",
};

function Badge({ children, type }: BadgeProps) {
  return (
    <span className={clsx(badgeStyles.badge, badgeStyles[type])}>
      {children}
    </span>
  );
}

export default Badge;
